//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practik
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        public int ID_Employee { get; set; }
        public string SurnameEmployee { get; set; }
        public string NameEmployee { get; set; }
        public string MiddleNameEmployee { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public int Role_ID { get; set; }
        public string Email { get; set; }
    
        public virtual Roles Roles { get; set; }
    }
}
