//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practik
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payments
    {
        public int ID_Payment { get; set; }
        public int PaymentMethod_ID { get; set; }
        public int Client_ID { get; set; }
        public decimal PaymentAmount { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual PaymentMethods PaymentMethods { get; set; }
    }
}
