//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practik
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.OrderDetails = new HashSet<OrderDetails>();
            this.Warehouse = new HashSet<Warehouse>();
        }
    
        public int ID_Product { get; set; }
        public string ProductName { get; set; }
        public string Article { get; set; }
        public int ProductCategory_ID { get; set; }
        public int Manufacturer_ID { get; set; }
        public int ProductUnit_ID { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public decimal Price { get; set; }
        public int ProductStatus_ID { get; set; }
    
        public virtual Manufacturers Manufacturers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetails> OrderDetails { get; set; }
        public virtual ProductCategories ProductCategories { get; set; }
        public virtual ProductUnits ProductUnits { get; set; }
        public virtual ProductStatuses ProductStatuses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Warehouse> Warehouse { get; set; }
    }
}
