//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practik
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warehouse
    {
        public int ID_Warehouse { get; set; }
        public int Product_ID { get; set; }
        public Nullable<int> ProductLocation_ID { get; set; }
        public int Quantity { get; set; }
        public int ProductStatus_ID { get; set; }
    
        public virtual ProductLocation ProductLocation { get; set; }
        public virtual Products Products { get; set; }
        public virtual ProductStatuses ProductStatuses { get; set; }
    }
}
